FROM node:20-alpine

WORKDIR /app

# Copiar solo package.json
COPY package*.json ./

# Instalar dependencias DENTRO del contenedor
RUN npm ci

# Copiar el resto del código
COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]